<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>radius</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>Radius</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(if|unless)</string>
			<key>name</key>
			<string>keyword.control.radius</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(r:.[-_a-zA-Z0-9:]+)</string>
			<key>name</key>
			<string>entity.name.tag.radius</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;[\w|/][^r:|^!|^/r:].*&gt;)</string>
			<key>name</key>
			<string>entity.name.tag.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([_a-zA-Z-]+)=</string>
			<key>name</key>
			<string>entity.other.attribute-name.radius</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.radius</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.radius</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;[!%]--|&lt;r:comment&gt;</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.radius</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--%?&gt;|&lt;/r:comment&gt;</string>
			<key>name</key>
			<string>comment.block.radius</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.radius</string>
	<key>uuid</key>
	<string>EE991CFA-6906-4ED2-B423-CB10DBA978C0</string>
</dict>
</plist>
